package reddit_compat

type Comment struct {
	AllAwardings                 []any     `json:"all_awardings,nilasempty"`
	ApprovedAtUtc                any       `json:"approved_at_utc,omitempty"`
	ApprovedBy                   any       `json:"approved_by,omitempty"`
	Archived                     bool      `json:"archived"`
	AssociatedAward              any       `json:"associated_award,omitempty"`
	Author                       string    `json:"author,omitempty"`
	AuthorFlairBackgroundColor   any       `json:"author_flair_background_color,omitempty"`
	AuthorFlairCssClass          any       `json:"author_flair_css_class,omitempty"`
	AuthorFlairRichtext          []any     `json:"author_flair_richtext,omitempty"`
	AuthorFlairTemplateID        any       `json:"author_flair_template_id,omitempty"`
	AuthorFlairText              any       `json:"author_flair_text,omitempty"`
	AuthorFlairTextColor         any       `json:"author_flair_text_color,omitempty"`
	AuthorFlairType              string    `json:"author_flair_type,omitempty"`
	AuthorFullname               string    `json:"author_fullname,omitempty"`
	AuthorIsBlocked              bool      `json:"author_is_blocked"`
	AuthorPatreonFlair           bool      `json:"author_patreon_flair"`
	AuthorPremium                bool      `json:"author_premium"`
	Awarders                     []any     `json:"awarders,omitempty"`
	BannedAtUtc                  any       `json:"banned_at_utc,omitempty"`
	BannedBy                     any       `json:"banned_by,omitempty"`
	Body                         string    `json:"body,omitempty"`
	BodyHtml                     string    `json:"body_html,omitempty"`
	CanGild                      bool      `json:"can_gild,omitempty"`
	CanModPost                   bool      `json:"can_mod_post"`
	Children                     []string  `json:"children,nilasempty"`
	Collapsed                    bool      `json:"collapsed"`
	CollapsedBecauseCrowdControl any       `json:"collapsed_because_crowd_control,omitempty"`
	CollapsedReason              *string   `json:"collapsed_reason"`
	CollapsedReasonCode          *string   `json:"collapsed_reason_code"`
	CommentType                  any       `json:"comment_type,omitempty"`
	Controversiality             int       `json:"controversiality,omitempty"`
	Count                        int       `json:"count,omitempty"`
	Created                      int       `json:"created,omitempty"`
	CreatedUtc                   int       `json:"created_utc,omitempty"`
	Depth                        int       `json:"depth"`
	Distinguished                any       `json:"distinguished"`
	Downs                        int       `json:"downs,omitempty"`
	Edited                       bool      `json:"edited"`
	Gilded                       int       `json:"gilded,omitempty"`
	Gildings                     *struct{} `json:"gildings,omitempty"`
	ID                           string    `json:"id"`
	IsSubmitter                  bool      `json:"is_submitter"`
	Likes                        any       `json:"likes,omitempty"`
	LinkID                       string    `json:"link_id,omitempty"`
	Locked                       bool      `json:"locked"`
	ModNote                      any       `json:"mod_note,omitempty"`
	ModReasonBy                  any       `json:"mod_reason_by,omitempty"`
	ModReasonTitle               any       `json:"mod_reason_title,omitempty"`
	ModReports                   []any     `json:"mod_reports"`
	Name                         string    `json:"name"`
	NoFollow                     bool      `json:"no_follow"`
	NumReports                   any       `json:"num_reports,omitempty"`
	ParentID                     string    `json:"parent_id"`
	Permalink                    string    `json:"permalink,omitempty"`
	RemovalReason                any       `json:"removal_reason,omitempty"`
	Replies                      any       `json:"replies"`
	ReportReasons                any       `json:"report_reasons,omitempty"`
	Saved                        bool      `json:"saved"`
	Score                        int       `json:"score"`
	ScoreHidden                  bool      `json:"score_hidden"`
	SendReplies                  bool      `json:"send_replies,omitempty"`
	Stickied                     bool      `json:"stickied"`
	Subreddit                    string    `json:"subreddit,omitempty"`
	SubredditID                  string    `json:"subreddit_id,omitempty"`
	SubredditNamePrefixed        string    `json:"subreddit_name_prefixed,omitempty"`
	SubredditType                string    `json:"subreddit_type,omitempty"`
	TopAwardedType               any       `json:"top_awarded_type,omitempty"`
	TotalAwardsReceived          int       `json:"total_awards_received,omitempty"`
	TreatmentTags                []any     `json:"treatment_tags,omitempty"`
	UnrepliableReason            any       `json:"unrepliable_reason,omitempty"`
	Ups                          int       `json:"ups,omitempty"`
	UserReports                  []any     `json:"user_reports,omitempty"`
}
