package reddit_compat

type CommentContribSettings struct {
	AllowedMediaTypes []string `json:"allowed_media_types"`
}

type Subreddit struct {
	AcceptFollowers                  *bool                  `json:"accept_followers"`
	AccountsActive                   any                    `json:"accounts_active"`
	AccountsActiveIsFuzzed           *bool                  `json:"accounts_active_is_fuzzed"`
	ActiveUserCount                  any                    `json:"active_user_count"`
	AdvertiserCategory               *string                `json:"advertiser_category"`
	AllOriginalContent               *bool                  `json:"all_original_content"`
	AllowChatPostCreation            bool                   `json:"allow_chat_post_creation"`
	AllowDiscovery                   *bool                  `json:"allow_discovery"`
	AllowGalleries                   *bool                  `json:"allow_galleries"`
	AllowImages                      *bool                  `json:"allow_images"`
	AllowPolls                       *bool                  `json:"allow_polls"`
	AllowPredictionContributors      bool                   `json:"allow_prediction_contributors"`
	AllowPredictions                 bool                   `json:"allow_predictions"`
	AllowPredictionsTournament       bool                   `json:"allow_predictions_tournament"`
	AllowTalks                       bool                   `json:"allow_talks"`
	AllowVideogifs                   bool                   `json:"allow_videogifs"`
	AllowVideos                      bool                   `json:"allow_videos"`
	AllowedMediaInComments           []string               `json:"allowed_media_in_comments"`
	BannerBackgroundColor            *string                `json:"banner_background_color"`
	BannerBackgroundImage            string                 `json:"banner_background_image"`
	BannerImg                        *string                `json:"banner_img"`
	BannerSize                       []int                  `json:"banner_size"`
	CanAssignLinkFlair               bool                   `json:"can_assign_link_flair"`
	CanAssignUserFlair               bool                   `json:"can_assign_user_flair"`
	CollapseDeletedComments          *bool                  `json:"collapse_deleted_comments"`
	CommentContributionSettings      CommentContribSettings `json:"comment_contribution_settings"`
	CommentScoreHideMins             *int                   `json:"comment_score_hide_mins"`
	CommunityIcon                    string                 `json:"community_icon"`
	CommunityReviewed                *bool                  `json:"community_reviewed"`
	ContentCategory                  string                 `json:"content_category,omitempty"`
	Created                          float64                `json:"created"`
	CreatedUtc                       float64                `json:"created_utc"`
	Description                      *string                `json:"description"`
	DescriptionHtml                  *string                `json:"description_html"`
	DisableContributorRequests       *bool                  `json:"disable_contributor_requests"`
	DisplayName                      string                 `json:"display_name"`
	DisplayNamePrefixed              string                 `json:"display_name_prefixed"`
	EmojisCustomSize                 []int                  `json:"emojis_custom_size"`
	EmojisEnabled                    bool                   `json:"emojis_enabled"`
	FreeFormReports                  *bool                  `json:"free_form_reports"`
	HasMenuWidget                    bool                   `json:"has_menu_widget"`
	HeaderImg                        *string                `json:"header_img"`
	HeaderSize                       []int                  `json:"header_size"`
	HeaderTitle                      *string                `json:"header_title"`
	HideAds                          *bool                  `json:"hide_ads"`
	IconImg                          *string                `json:"icon_img"`
	IconSize                         []int                  `json:"icon_size"`
	ID                               string                 `json:"id"`
	IsChatPostFeatureEnabled         bool                   `json:"is_chat_post_feature_enabled"`
	IsCrosspostableSubreddit         bool                   `json:"is_crosspostable_subreddit"`
	IsEnrolledInNewModmail           any                    `json:"is_enrolled_in_new_modmail"`
	KeyColor                         *string                `json:"key_color"`
	Lang                             *string                `json:"lang"`
	LinkFlairEnabled                 *bool                  `json:"link_flair_enabled"`
	LinkFlairPosition                *string                `json:"link_flair_position"`
	MobileBannerImage                *string                `json:"mobile_banner_image"`
	Name                             string                 `json:"name"`
	NotificationLevel                any                    `json:"notification_level"`
	OriginalContentTagEnabled        *bool                  `json:"original_content_tag_enabled"`
	Over18                           *bool                  `json:"over18"`
	PredictionLeaderboardEntryType   string                 `json:"prediction_leaderboard_entry_type"`
	PrimaryColor                     *string                `json:"primary_color"`
	PublicDescription                string                 `json:"public_description"`
	PublicDescriptionHtml            *string                `json:"public_description_html"`
	PublicTraffic                    *bool                  `json:"public_traffic"`
	Quarantine                       *bool                  `json:"quarantine"`
	RestrictCommenting               *bool                  `json:"restrict_commenting"`
	RestrictPosting                  *bool                  `json:"restrict_posting"`
	ShouldArchivePosts               *bool                  `json:"should_archive_posts"`
	ShouldShowMediaInCommentsSetting bool                   `json:"should_show_media_in_comments_setting"`
	ShowMedia                        *bool                  `json:"show_media"`
	ShowMediaPreview                 *bool                  `json:"show_media_preview"`
	SpoilersEnabled                  *bool                  `json:"spoilers_enabled"`
	SubmissionType                   *string                `json:"submission_type"`
	SubmitLinkLabel                  *string                `json:"submit_link_label"`
	SubmitText                       *string                `json:"submit_text"`
	SubmitTextHtml                   *string                `json:"submit_text_html"`
	SubmitTextLabel                  *string                `json:"submit_text_label"`
	SubredditType                    string                 `json:"subreddit_type"`
	Subscribers                      *int                   `json:"subscribers"`
	SuggestedCommentSort             *string                `json:"suggested_comment_sort"`
	Title                            string                 `json:"title"`
	URL                              string                 `json:"url"`
	UserCanFlairInSr                 any                    `json:"user_can_flair_in_sr"`
	UserFlairBackgroundColor         any                    `json:"user_flair_background_color"`
	UserFlairCssClass                any                    `json:"user_flair_css_class"`
	UserFlairEnabledInSr             *bool                  `json:"user_flair_enabled_in_sr"`
	UserFlairPosition                *string                `json:"user_flair_position"`
	UserFlairRichtext                []any                  `json:"user_flair_richtext"`
	UserFlairTemplateID              any                    `json:"user_flair_template_id"`
	UserFlairText                    any                    `json:"user_flair_text"`
	UserFlairTextColor               any                    `json:"user_flair_text_color"`
	UserFlairType                    string                 `json:"user_flair_type"`
	UserHasFavorited                 any                    `json:"user_has_favorited"`
	UserIsBanned                     any                    `json:"user_is_banned"`
	UserIsContributor                any                    `json:"user_is_contributor"`
	UserIsModerator                  any                    `json:"user_is_moderator"`
	UserIsMuted                      any                    `json:"user_is_muted"`
	UserIsSubscriber                 any                    `json:"user_is_subscriber"`
	UserSrFlairEnabled               any                    `json:"user_sr_flair_enabled"`
	UserSrThemeEnabled               *bool                  `json:"user_sr_theme_enabled"`
	VideostreamLinksCount            int                    `json:"videostream_links_count,omitempty"`
	WhitelistStatus                  *string                `json:"whitelist_status"`
	WikiEnabled                      *bool                  `json:"wiki_enabled"`
	Wls                              *int                   `json:"wls"`
}
